//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePartWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Contact
    {
        public string Company_name { get; set; }
        public string Spare_ID { get; set; }
        public string Contact_person { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual SPAREPART SPAREPART { get; set; }
    }
}
