//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePartWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Person
    {
        public string Contact_tel { get; set; }
        public int Vendor_ID { get; set; }
        public string Contact_name { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
