//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePartWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_Sparepart
    {
        public string Equip_ID { get; set; }
        public string Spare_ID { get; set; }
        public int Qty_sparepart_used { get; set; }
        public int Man_hrs_used { get; set; }
        public System.DateTime Replacement_date { get; set; }
    
        public virtual Equipment_1 Equipment_1 { get; set; }
        public virtual SPAREPART SPAREPART { get; set; }
    }
}
