//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePartWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment_1()
        {
            this.Equipment_Sparepart = new HashSet<Equipment_Sparepart>();
            this.Maintenanace_Equipment = new HashSet<Maintenanace_Equipment>();
            this.Used_Part = new HashSet<Used_Part>();
        }
    
        public string Equip_ID { get; set; }
        public string Equip_name { get; set; }
        public string Equip_location { get; set; }
        public System.DateTime Purchase_date { get; set; }
        public int Exp_lifetime { get; set; }
        public int Avg_man_hrs_shutdown { get; set; }
        public decimal Purchase_price { get; set; }
        public decimal Est_cost_brkdown { get; set; }
    
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_Sparepart> Equipment_Sparepart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenanace_Equipment> Maintenanace_Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Used_Part> Used_Part { get; set; }
    }
}
