//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePartWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenanace_Equipment
    {
        public int Main_ID { get; set; }
        public string Equip_ID { get; set; }
        public System.DateTime Main_date { get; set; }
        public System.TimeSpan Main_time { get; set; }
        public decimal Main_cost { get; set; }
        public int Amt_time_equip_down { get; set; }
        public int Amt_time_to_repair { get; set; }
        public string Process_desc { get; set; }
    
        public virtual Equipment_1 Equipment_1 { get; set; }
        public virtual Maintenance_1 Maintenance_1 { get; set; }
    }
}
