//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePartWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance_1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maintenance_1()
        {
            this.Maintenanace_Equipment = new HashSet<Maintenanace_Equipment>();
            this.Used_Part = new HashSet<Used_Part>();
            this.SPAREPARTs = new HashSet<SPAREPART>();
        }
    
        public int Main_ID { get; set; }
        public string Main_name { get; set; }
        public string Type_shutdown { get; set; }
        public string Type_breakdown { get; set; }
        public Nullable<int> Total_man_hrs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenanace_Equipment> Maintenanace_Equipment { get; set; }
        public virtual Maintenance_Type Maintenance_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Used_Part> Used_Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPAREPART> SPAREPARTs { get; set; }
    }
}
