//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePartWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.Sparepart_Vendor_1 = new HashSet<Sparepart_Vendor_1>();
        }
    
        public string Transaction_no { get; set; }
        public System.DateTime Order_release_date { get; set; }
        public Nullable<System.DateTime> Order_recieve_date { get; set; }
        public Nullable<int> Lead_time { get; set; }
        public int Qty_purchased { get; set; }
        public decimal Unit_price { get; set; }
        public Nullable<decimal> Total_amt_paid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sparepart_Vendor_1> Sparepart_Vendor_1 { get; set; }
    }
}
