//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePartWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sparepart_Vendor_1
    {
        public int Vendor_ID { get; set; }
        public string Spare_ID { get; set; }
        public string Transaction_no { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual SPAREPART SPAREPART { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
