//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePartWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPAREPART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPAREPART()
        {
            this.Company_Contact = new HashSet<Company_Contact>();
            this.Equipment_Sparepart = new HashSet<Equipment_Sparepart>();
            this.Sparepart_Vendor_1 = new HashSet<Sparepart_Vendor_1>();
            this.Maintenance_1 = new HashSet<Maintenance_1>();
        }
    
        public string Spare_ID { get; set; }
        public Nullable<System.DateTime> Purchase_date { get; set; }
        public string Name { get; set; }
        public decimal Unit_cost { get; set; }
        public string Type_slow_part { get; set; }
        public string Type_fast_part { get; set; }
        public int Exp_lifeTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_Contact> Company_Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_Sparepart> Equipment_Sparepart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sparepart_Vendor_1> Sparepart_Vendor_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_1> Maintenance_1 { get; set; }
    }
}
