//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparePartWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Spare_Part_SystemEntities : DbContext
    {
        public Spare_Part_SystemEntities()
            : base("name=Spare_Part_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Company_Contact> Company_Contact { get; set; }
        public virtual DbSet<Contact_Person> Contact_Person { get; set; }
        public virtual DbSet<Equipment_1> Equipment_1 { get; set; }
        public virtual DbSet<Equipment_Sparepart> Equipment_Sparepart { get; set; }
        public virtual DbSet<Maintenanace_Equipment> Maintenanace_Equipment { get; set; }
        public virtual DbSet<Maintenance_1> Maintenance_1 { get; set; }
        public virtual DbSet<Maintenance_Type> Maintenance_Type { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<SPAREPART> SPAREPARTs { get; set; }
        public virtual DbSet<Sparepart_Vendor_1> Sparepart_Vendor_1 { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Used_Part> Used_Part { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
